### PR TITLE
Fix: mix format crashes in umbrella projects

### LINKED ISSUE #231: mix format crashes at umbrella root with MatchError
Running `mix format` from an umbrella project root crashes with:

```
** (MatchError) no match of right hand side value: {[%{name: MyUmbrella.MixProject, ...}], []}
    (mix) lib/mix/project_stack.ex:68: Mix.ProjectStack.on_recursing_root/1
```

## Reproduction

1. Create umbrella with `mix new my_umbrella --umbrella`
2. Add Ash/Spark to a sub-app
3. Configure Spark.Formatter plugin in sub-app's .formatter.exs
4. Run `mix format` from umbrella root

## Root Cause

Regression from #228 fix. The `Mix.Task.run("compile")` call added in 9eddbeb 
causes recursive compilation during formatting, which Mix.ProjectStack doesn't support.

## Workaround

Run format from within sub-apps instead of umbrella root.

Fix submitted in #230

### PR DESCRIPTION
**Pull request by matthewsinclair**
Running `mix format` at umbrella root crashes with a MatchError in Mix.ProjectStack.

## The Problem

The fix for #228 (commits 9eddbeb and 0d1048a) added compilation before formatting 
to ensure modules are available. This breaks umbrella projects because calling 
`Mix.Task.run("compile")` from within a formatter plugin triggers recursive 
compilation, violating Mix.ProjectStack's expectations.

## Changes

- Added `safe_compile/0` that checks `Mix.Project.umbrella?()` before compiling
- Skips compilation at umbrella root, runs normally elsewhere
- Added graceful error handling when modules can't be loaded
- Improved error messages in the mix task for umbrella users
- Added test coverage

Fixes #231

### CODE REVIEW

File: lib/mix/tasks/spark.formatter.ex [hunk 1]
```diff
@@ -10,7 +10,11 @@ if Code.ensure_loaded?(Sourceror) do
 
     @spec run(term) :: no_return
     def run(opts) do
-      Mix.Task.run("compile")
+      # Compile if safe to do so (not at umbrella root)
+      unless Mix.Project.umbrella?() do
```
Comment (zachdaniel) [inline lib/mix/tasks/spark.formatter.ex]:
```suggestion
      if not Mix.Project.umbrella?() do
```

`unless` is deprecated.

**Comment by zachdaniel** [comment]
Please fix credo then I'll merge 🙇
